version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    ports:
      - 3001:3001
  
  frontend:
    build:
      context: .
      dockerfile: Docker/frontend/Dockerfile
    ports:
      - 3000:3000